import { MongoClient } from "mongodb"; 
import MeetupList from '@/components/meetups/MeetupList'
import Head from 'next/head'

const DUMMY = [
  {
      id: 'd1',
      title: 'First meetup',
      image: 'https://s3.us-east-1.amazonaws.com/co-assets/assets/images/_fbTw/good-meeting.jpg',
      address: '123 First Street',
      description: 'This is the first meetup'
  },
  {
      id: 'd2',
      title: 'Second meetup',
      image: 'https://website2021-live-e3e78fbbd3cc41f2847799-7c49c59.divio-media.com/filer_public/30/eb/30eb9913-5b2a-4ac7-9a8f-51d12bf11392/meeting-moderation.png',
      address: '456 Second Street',
      description: 'This is the second meetup'
  },
  {
      id: 'd3',
      title: 'Third meetup',
      image: 'https://knowledge.wharton.upenn.edu/wp-content/uploads/2022/10/10.26.22-nano-tool-25-minute-meeting-900x612.jpg',
      address: '789 Third Street',
      description: 'This is the third meetup'
  }
]

export default function Home(props) {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MeetupList meetups={props.meetups} />

    </>
  )
}

//Static Side Generation - runs during the build process

export async function getStaticProps() {
  const client = await MongoClient.connect('mongodb+srv://nancyhou958:not4u2no@cluster0.cobn8bc.mongodb.net/?retryWrites=true&w=majority');
  const db = client.db();
  const meetupCollection = db.collection('meetups');

  const meetups = await meetupCollection.find().toArray();

  client.close();

  return {
    props: {
      meetups: meetups.map(meetup => ({
        title: meetup.title,
        image: meetup.image,
        address: meetup.address,
        id: meetup._id.toString()
      }))
    },
    revalidate: 10 //time in seconds

  }
} 

//Server Side Renddering - runs after deployment
/*export async function getServerSideProps() {
  return {
    props: {
      meetups: DUMMY
    }
  }
}*/